"use server"

import {
  fixtureActor,
  fixtureAuthority,
  type FixtureActor,
  type FixtureRecord,
} from "@/lib/authority"
import { addItem, fixtureProtocol, ITEMS_AXIS } from "@/lib/protocol"
import {
  acceptMutation,
  allowMutation,
  allowMutationScreening,
  bindMutation,
  createNextMutationAction,
  denyMutation,
  refuseMutation,
  type MutationCommand,
} from "headcanon/next/server"
import type { InMemoryReader, InMemoryTransaction } from "headcanon/testing"

const addItemCommand: MutationCommand<
  typeof addItem,
  FixtureActor,
  InMemoryReader<FixtureRecord>,
  InMemoryTransaction<FixtureRecord>,
  null,
  null
> = {
  screen: ({ actor }) =>
    actor.role === "editor" ? allowMutationScreening(null) : denyMutation(),
  admit: () => allowMutation(null),
  execute({ tx, args, stamp }) {
    const current = tx.read()
    if (current.items.includes(args.text)) {
      return refuseMutation("item-refused")
    }
    const revision = current.revision + 1
    tx.write({ items: [...current.items, args.text], revision })
    stamp.record(ITEMS_AXIS, revision)
    return acceptMutation()
  },
}

/**
 * The fixture's one Server Action, generated by the package: it parses the
 * envelope, deduplicates by receipt, stamps, and finalizes with `updateTag`
 * and server `refresh()`, so the accepted canon rides back on this action's
 * own RSC payload. The fixture supplies only the actor and the command.
 */
export const applyFixtureMutation = createNextMutationAction({
  protocol: fixtureProtocol,
  actor: fixtureActor,
  authority: fixtureAuthority,
  commands: [bindMutation(addItem, addItemCommand)],
  // The fixture has no realtime transport: the router carrier alone brings
  // canon, so there is nothing to publish to.
  invalidations: { publish: () => undefined },
  reportInvalidationFailure: (failure) => {
    console.error("fixture invalidation publication failed", failure)
  },
})
