"use server"

import { fixtureBinder } from "@/lib/authority"
import { addItem, fixtureProtocol, ITEMS_AXIS } from "@/lib/protocol"
import {
  acceptMutation,
  allowMutation,
  allowMutationScreening,
  createNextMutationAction,
  denyMutation,
  refuseMutation,
} from "headcanon/next/server"

/**
 * The fixture's one Server Action, generated by the package: it parses the
 * envelope, deduplicates by receipt, stamps, and finalizes with `updateTag`
 * and server `refresh()`, so the accepted canon rides back on this action's
 * own RSC payload. The fixture supplies only the binder and the command.
 */
export const applyFixtureMutation = createNextMutationAction({
  protocol: fixtureProtocol,
  binder: fixtureBinder,
  // No `invalidations`: the fixture has no realtime transport, and the router
  // carrier alone brings canon back.
  commands: [
    fixtureBinder.bind(addItem, {
      screen: ({ actor }) =>
        actor.role === "editor" ? allowMutationScreening(null) : denyMutation(),
      admit: () => allowMutation(null),
      execute({ tx, args, stamp }) {
        const current = tx.read()
        if (current.items.includes(args.text)) {
          return refuseMutation("item-refused")
        }
        const revision = current.revision + 1
        tx.write({ items: [...current.items, args.text], revision })
        stamp.record(ITEMS_AXIS, revision)
        return acceptMutation()
      },
    }),
  ],
})
