"use client"

import { unstable_rethrow, useRouter } from "next/navigation"
import { useMemo } from "react"
import { err, ok, type Result } from "serializable-result"

import type {
  MutationEnvelope,
  MutationExecutorError,
  MutationTerminalOutcome,
  ProtocolIdentity,
} from "../core/authority"
import type {
  AnyMutationDefinition,
  MutationRefusalOf,
  ProtocolDefinition,
  ProtocolInvocation,
} from "../core/protocol"
import type { AcceptedStamp } from "../core/revisions"
import { createPredictedRootHook } from "../predicted-root"
import {
  createObservedRoot,
  RetryableDeliveryError,
  TerminalDeliveryError,
  type ObservedRootOptions,
  type PredictedRootHook,
  type PredictedRootOptions,
} from "../react"
import type { RefreshAdapter } from "../refresh"

/** Grace period allowing a Server Action's RSC response to carry acceptance. */
export const ROUTER_ACCEPTANCE_GRACE_MS = 250

type ProtocolMutation<Protocol> =
  Protocol extends ProtocolDefinition<string, infer Mutations>
    ? Mutations[number]
    : never

/**
 * The Server Action `createNextMutationAction` generates for one protocol.
 * The outcome carries a phantom {@link ProtocolIdentity}: a generated action
 * admits `unknown` envelopes, so its parameter cannot distinguish protocols.
 * The identity tag makes binding the wrong protocol's action a local type
 * error even when two protocols share a refusal shape.
 * @param envelope Parsed protocol envelope to deliver.
 * @returns A promise for the terminal authority result.
 */
export type NextMutationAction<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
> = (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<
    MutationTerminalOutcome<MutationRefusalOf<ProtocolMutation<Protocol>>>,
    MutationExecutorError
  > &
    ProtocolIdentity<Protocol["id"]>
>

/**
 * Root options whose refresh carrier the Next binding may supply: when
 * `refresh` is omitted, the App Router carrier ({@link useRouterRefresh}) is
 * used.
 */
type WithRouterCarrier<
  Options extends { readonly refresh: () => RefreshAdapter },
> = Omit<Options, "refresh"> & { readonly refresh?: Options["refresh"] }

/**
 * The explicit form: the caller's own sender, plus every other
 * {@link PredictedRootOptions} field, with the App Router as the default
 * refresh carrier.
 */
export type NextPredictedRootOptions<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
> = WithRouterCarrier<PredictedRootOptions<Protocol>>

/**
 * The golden-path form: a raw generated Server Action implies the standard
 * sender adapter. Every other field is a {@link NextPredictedRootOptions}
 * field, forwarded unchanged.
 */
export type NextActionPredictedRootOptions<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
> = Omit<NextPredictedRootOptions<Protocol>, "send"> & {
  /** The Server Action generated by `createNextMutationAction`. */
  readonly action: NextMutationAction<Protocol>
}

/** Optional App Router refresh and invalidation dependencies for an observed root. */
export type NextObservedRootOptions = WithRouterCarrier<ObservedRootOptions>

/** The Next binding's one decision about the default refresh carrier. */
function withRouterCarrier<
  Options extends { readonly refresh?: () => RefreshAdapter },
>(options: Options): Options & { readonly refresh: () => RefreshAdapter } {
  return { ...options, refresh: options.refresh ?? useRouterRefresh }
}

/**
 * Creates a predicted-root hook for a Next.js App Router surface.
 *
 * The action form is the standard path: it supplies the sender adapter for a
 * generated Server Action. The explicit `send` form remains available for
 * snapshot carriers, tests, and unusual delivery adapters. Both forms default
 * refresh to `router.refresh()`, and both run Next's `unstable_rethrow` on
 * every delivery throw first: framework control flow (`redirect()`,
 * `notFound()`, `forbidden()`, `unauthorized()`) cancels the mutation and
 * propagates to Next instead of becoming uncertain delivery. The generated
 * action must use the same protocol object as the root; its phantom protocol
 * identity makes accidental cross-protocol binding a type error. Omit
 * `invalidations` when the surface intentionally has no push transport.
 *
 * `DELIVERY_WAIT_MS` bounds the root's own Action, not the Server Action
 * call. Next sends each call through the App Router's action queue, which
 * keeps the router state on a pending promise inside a transition until the
 * HTTP response arrives. React renders all transitions together, so while one
 * call is unanswered no transition in the app commits, and the queue does not
 * send the next Server Action call (a `retryDelivery()` included). A
 * navigation still proceeds. Next exposes no way to abort the call, so bound
 * it on the server: give the command's external work and database waits a
 * deadline below the platform's request limit, so that every call answers.
 *
 * @param options Protocol and either generated action or explicit delivery dependencies.
 * @returns A predicted-root hook for the Next App Router.
 */
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  options: NextActionPredictedRootOptions<Protocol>
): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(options: NextPredictedRootOptions<Protocol>): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  options:
    | NextActionPredictedRootOptions<Protocol>
    | NextPredictedRootOptions<Protocol>
): PredictedRootHook<Protocol> {
  return createPredictedRootHook(
    withRouterCarrier(explicitSender(options)),
    unstable_rethrow
  )
}

function explicitSender<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
>(
  options:
    | NextActionPredictedRootOptions<Protocol>
    | NextPredictedRootOptions<Protocol>
): NextPredictedRootOptions<Protocol> {
  if (!("action" in options)) return options
  const { action, ...rest } = options
  return { ...rest, send: createNextMutationSender<Protocol>(action) }
}

/** An observed root whose canon arrives as RSC props through the App Router.
 * @param options Optional refresh and invalidation dependencies.
 * @returns An observed-root hook.
 */
export function createNextObservedRoot(options: NextObservedRootOptions = {}) {
  return createObservedRoot(withRouterCarrier(options))
}

/**
 * Adapts a generated Server Action to the explicit predicted-root delivery
 * seam. Prefer the `action` form of {@link createNextPredictedRoot} for the
 * standard App Router carrier.
 *
 * An accepted outcome becomes the stamp and a refused outcome the domain
 * refusal. Exhausted contention throws {@link RetryableDeliveryError}, so the
 * root redelivers the same envelope. A denial, or any other executor error
 * (the envelope, its arguments, or its mutation ID was refused), throws
 * {@link TerminalDeliveryError}: the answer is final and a retry would get it
 * again.
 * @param action Generated Server Action for one protocol.
 * @returns A sender adapter returning accepted stamps or typed refusals.
 */
export function createNextMutationSender<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  action: NextMutationAction<Protocol>
): (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<AcceptedStamp, MutationRefusalOf<ProtocolMutation<Protocol>>>
> {
  return async (envelope) => {
    const outcome = await action(envelope)
    if (!outcome.ok) {
      if (outcome.error.code === "contention") {
        throw new RetryableDeliveryError("mutation authority contention")
      }
      throw new TerminalDeliveryError({
        kind: "undeliverable",
        error: outcome.error,
      })
    }

    switch (outcome.value.kind) {
      case "accepted":
        return ok(outcome.value.stamp)
      case "refused":
        return err(outcome.value.error)
      case "denied":
        throw new TerminalDeliveryError({ kind: "denied" })
    }
  }
}

/** Requests a new RSC payload through the App Router.
 * @returns A refresh adapter backed by `router.refresh()`.
 */
export function useRouterRefresh(): RefreshAdapter {
  const router = useRouter()

  return useMemo(
    () => ({
      acceptanceGraceMs: ROUTER_ACCEPTANCE_GRACE_MS,
      request: () => router.refresh(),
    }),
    [router]
  )
}
