"use client"

import { unstable_rethrow, useRouter } from "next/navigation"
import { useMemo } from "react"
import { err, ok, type Result } from "serializable-result"

import type {
  MutationEnvelope,
  MutationExecutorError,
  MutationTerminalOutcome,
  ProtocolIdentity,
} from "../core/authority"
import type {
  AnyProtocolDefinition,
  MutationRefusalOf,
  ProtocolInvocation,
  ProtocolMutation,
} from "../core/protocol"
import type { AcceptedStamp } from "../core/revisions"
import {
  createObservedRoot,
  RetryableDeliveryError,
  TerminalDeliveryError,
  type ObservedRootOptions,
  type PredictedRootHook,
  type PredictedRootOptions,
} from "../react"
import { createPredictedRootHook } from "../react/predicted-root"
import type { RefreshAdapter } from "../react/refresh"

/** Grace period allowing a Server Action's RSC response to carry acceptance. */
export const ROUTER_ACCEPTANCE_GRACE_MS = 250

/**
 * The Server Action `createNextMutationAction` generates for one protocol. Its
 * outcome carries the protocol's {@link ProtocolIdentity}, so binding another
 * protocol's action is a type error.
 * @param envelope Parsed protocol envelope to deliver.
 * @returns A promise for the terminal authority result.
 */
export type NextMutationAction<Protocol extends AnyProtocolDefinition> = (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<
    MutationTerminalOutcome<MutationRefusalOf<ProtocolMutation<Protocol>>>,
    MutationExecutorError
  > &
    ProtocolIdentity<Protocol["id"]>
>

/**
 * Root options whose refresh carrier the Next binding may supply: when
 * `refresh` is omitted, the App Router carrier ({@link useRouterRefresh}) is
 * used.
 */
type WithRouterCarrier<
  Options extends { readonly refresh: () => RefreshAdapter },
> = Omit<Options, "refresh"> & {
  /** The root's refresh carrier hook; defaults to {@link useRouterRefresh}. */
  readonly refresh?: Options["refresh"]
}

/**
 * The explicit form: the caller's own sender, plus every other
 * {@link PredictedRootOptions} field, with the App Router as the default
 * refresh carrier.
 */
export type NextPredictedRootOptions<Protocol extends AnyProtocolDefinition> =
  WithRouterCarrier<PredictedRootOptions<Protocol>>

/**
 * The golden-path form: a raw generated Server Action implies the standard
 * sender adapter. Every other field is a {@link NextPredictedRootOptions}
 * field, forwarded unchanged.
 */
export type NextActionPredictedRootOptions<
  Protocol extends AnyProtocolDefinition,
> = Omit<NextPredictedRootOptions<Protocol>, "send"> & {
  /** The Server Action generated by `createNextMutationAction`. */
  readonly action: NextMutationAction<Protocol>
}

/** Optional App Router refresh and invalidation dependencies for an observed root. */
export type NextObservedRootOptions = WithRouterCarrier<ObservedRootOptions>

/** The Next binding's one decision about the default refresh carrier. */
function withRouterCarrier<
  Options extends { readonly refresh?: () => RefreshAdapter },
>(options: Options): Options & { readonly refresh: () => RefreshAdapter } {
  return { ...options, refresh: options.refresh ?? useRouterRefresh }
}

/**
 * Creates a predicted-root hook for a Next.js App Router surface.
 *
 * The action form is the standard path: it supplies the sender adapter for a
 * generated Server Action. The explicit `send` form remains available for
 * snapshot carriers, tests, and unusual delivery adapters. Both forms default
 * refresh to `router.refresh()`, and both run Next's `unstable_rethrow` on
 * every delivery throw first: framework control flow (`redirect()`,
 * `notFound()`, `forbidden()`, `unauthorized()`) cancels the mutation and
 * propagates to Next instead of becoming uncertain delivery. The generated
 * action must use the same protocol object as the root. Omit `invalidations`
 * when the surface intentionally has no push transport.
 *
 * `DELIVERY_WAIT_MS` does not bound the Server Action call. While one call is
 * unanswered, no transition in the app commits and later Server Action calls
 * (`retryDelivery()` included) wait behind it. A navigation still proceeds.
 * Give the command's external work and database waits a deadline below the
 * platform's request limit. See README, "A Server Action that does not
 * answer".
 *
 * @param options Protocol and either generated action or explicit delivery dependencies.
 * @returns A predicted-root hook for the Next App Router.
 */
export function createNextPredictedRoot<
  const Protocol extends AnyProtocolDefinition,
>(
  options: NextActionPredictedRootOptions<Protocol>
): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends AnyProtocolDefinition,
>(options: NextPredictedRootOptions<Protocol>): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends AnyProtocolDefinition,
>(
  options:
    | NextActionPredictedRootOptions<Protocol>
    | NextPredictedRootOptions<Protocol>
): PredictedRootHook<Protocol> {
  return createPredictedRootHook(
    withRouterCarrier(withActionSender(options)),
    unstable_rethrow
  )
}

function withActionSender<Protocol extends AnyProtocolDefinition>(
  options:
    | NextActionPredictedRootOptions<Protocol>
    | NextPredictedRootOptions<Protocol>
): NextPredictedRootOptions<Protocol> {
  if (!("action" in options)) return options
  const { action, ...rest } = options
  return { ...rest, send: createNextMutationSender<Protocol>(action) }
}

/** An observed root whose canon arrives as RSC props through the App Router.
 * @param options Optional refresh and invalidation dependencies.
 * @returns An observed-root hook.
 */
export function createNextObservedRoot(options: NextObservedRootOptions = {}) {
  return createObservedRoot(withRouterCarrier(options))
}

/**
 * Adapts a generated Server Action to the explicit predicted-root delivery
 * seam. Prefer the `action` form of {@link createNextPredictedRoot} for the
 * standard App Router carrier.
 *
 * An accepted outcome becomes the stamp and a refused outcome the domain
 * refusal. Exhausted contention throws {@link RetryableDeliveryError}, so the
 * root redelivers the same envelope. A denial, or any other executor error
 * (the envelope, its arguments, or its mutation ID was refused), throws
 * {@link TerminalDeliveryError}: the answer is final and a retry would get it
 * again.
 * @param action Generated Server Action for one protocol.
 * @returns A sender adapter returning accepted stamps or typed refusals.
 */
export function createNextMutationSender<
  const Protocol extends AnyProtocolDefinition,
>(
  action: NextMutationAction<Protocol>
): (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<AcceptedStamp, MutationRefusalOf<ProtocolMutation<Protocol>>>
> {
  return async (envelope) => {
    const outcome = await action(envelope)
    if (!outcome.ok) {
      if (outcome.error.code === "contention") {
        throw new RetryableDeliveryError("mutation authority contention")
      }
      throw new TerminalDeliveryError({
        kind: "undeliverable",
        error: outcome.error,
      })
    }

    switch (outcome.value.kind) {
      case "accepted":
        return ok(outcome.value.stamp)
      case "refused":
        return err(outcome.value.error)
      case "denied":
        throw new TerminalDeliveryError({ kind: "denied" })
    }
  }
}

/**
 * Returns the App Router refresh adapter: its `request` calls
 * `router.refresh()` for a new RSC payload, with
 * {@link ROUTER_ACCEPTANCE_GRACE_MS} of acceptance grace. The Next roots use
 * it when `refresh` is omitted; pass it as `refresh` to a `headcanon/react`
 * root.
 *
 * The router reports no failure to the root. In the browser, a refresh that
 * fails makes Next.js load the whole page again, which drops the root's queue
 * and unsaved drafts.
 * @returns A refresh adapter backed by `router.refresh()`.
 */
export function useRouterRefresh(): RefreshAdapter {
  const router = useRouter()

  return useMemo(
    () => ({
      acceptanceGraceMs: ROUTER_ACCEPTANCE_GRACE_MS,
      request: () => router.refresh(),
    }),
    [router]
  )
}
